[project]
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "torchcodec-test-debug"
platforms = ["linux-64",  "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]
download_src_03 = {cmd = "echo Download torchcodec src && mkdir -p ./.pixi_ws && git clone https://github.com/pytorch/torchcodec --branch v0.3.0 ./.pixi_ws/torchcodec", outputs=[".pixi_ws/torchcodec/README.md"]}
test_py = {cmd = "echo Run torchcodec python tests && pytest", cwd = "./.pixi_ws/torchcodec/test", depends-on = ["download_src_03"]}
# If there is any problem, run uninstall_src_deps to uninstall the source dependencies
cleanup_src_deps = {cmd = "echo Uninstall src deps && rm -rf ./.pixi_ws/"}

[dependencies]
python = "3.12.*"
pip = "*"
numpy = "*"
pytest = "*"

[pypi-options]
no-build-isolation = ["torchcodec"]

[feature.ffmpeg71.dependencies]
ffmpeg = "7.1.*"

[feature.ffmpeg70.dependencies]
ffmpeg = "7.0.*"

[feature.torchconda.dependencies]
pytorch = "2.7.*"

[feature.torchpip]
platforms = ["linux-64", "osx-arm64"]

[feature.torchpip.pypi-dependencies]
torch = "==2.7.*"

[feature.torchcodecpip]
platforms = ["linux-64", "osx-arm64"]

[feature.torchcodecpip.pypi-dependencies]
torchcodec = "==0.3.*"

[feature.torchcodecconda.dependencies]
# Build dependencies
cmake = "*"
make = "*"
ninja = "*"
cxx-compiler = "*"
pybind11 = "*"
pkg-config = "*"

[feature.torchcodecconda.pypi-dependencies]
# this is just v0.3.0 with https://github.com/pytorch/torchcodec/pull/656
torchcodec = { git = "https://github.com/traversaro/torchcodec.git", rev = "03removewerror" }

[environments]
default = {features = ["torchconda","ffmpeg71"], solve-group = "ffmpeg71"}
torchcondatorchcodecpipffmpeg71 = {features = ["torchconda","torchcodecpip","ffmpeg71"], solve-group = "ffmpeg71"}
allpipffmpeg71 = {features = ["torchpip","torchcodecpip","ffmpeg71"], solve-group = "ffmpeg71"}
allcondaffmpeg71 = {features = ["torchconda","torchcodecconda","ffmpeg71"], solve-group = "ffmpeg71"}
