name: CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build-with-pixi:
    name: '[pixi:${{ matrix.pixi_task }}:${{ matrix.pixi_env }}:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-22.04, macos-14]
        pixi_task: [test_py]
        pixi_env: [torchcondatorchcodecpipffmpeg71, allpipffmpeg71, allcondaffmpeg71]
        include:
          # pytorch and torchcodec wheels are not available on osx-64
          - os: macos-13
            pixi_env: allcondaffmpeg71

    steps:
    - uses: actions/checkout@v4

    - name: Print used environment (no conda) [Conda]
      shell: bash
      run: |
        env

    - uses: prefix-dev/setup-pixi@v0.8.6

    - name: Run the task ${{ matrix.pixi_task }}
      shell: bash -l {0}
      run: pixi run -e ${{ matrix.pixi_env }} ${{ matrix.pixi_task }}

