name: CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build-with-pixi:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-22.04, ubuntu-24.04-arm]

    steps:
    - uses: actions/checkout@v4

    - name: Print used environment (no conda) [Conda]
      shell: bash
      run: |
        env

    - uses: prefix-dev/setup-pixi@v0.8.6

    - name: Run C++ tests
      shell: bash -l {0}
      run: pixi run test_cxx

    - name: Run the Python tests
      shell: bash -l {0}
      run: pixi run test_py
